name: CI
on:
  push:
    branches: [master]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        ghc: ['9.0', '9.2', '9.4', '9.6']
        cabal: ['3.10']
        experimental: [false]
        include:
          - ghc: '9.12'
            cabal: '3.14'
            experimental: false
          - ghc: '9.10'
            cabal: '3.12'
            experimental: false
          - ghc: '9.8'
            cabal: '3.12'
            experimental: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install GHC and Cabal
        uses: haskell-actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - name: Install and test
        run: |
          cabal --version
          echo "$(ghc --version) "`
              `"[$(ghc --print-project-git-commit-id 2>/dev/null || echo '?')]"
          cabal update
          cabal build
          cabal install --lib
          echo 'module Main where main = putStrLn "Ok"' |
              ghc --frontend GhcStdin -ffrontend-opt="-o simple_ok"
          test $(./simple_ok) = Ok

