name: CI
on:
  push:
    branches: [master]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        ghc: [8.4.4, 8.6.5, 8.8.4, 8.10.7, 9.0.2, 9.2.5, 9.4.4]
        cabal: [3.8.1.0]
        experimental: [false]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install GHC and Cabal
        uses: haskell/actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - name: Install and test
        env:
          GHCVER: ${{ matrix.ghc }}
          CABALVER: ${{ matrix.cabal }}
        run: |
          set -e
          cabal --version
          echo "$(ghc --version) "`
              `"[$(ghc --print-project-git-commit-id 2>/dev/null || echo '?')]"
          if echo "$CABALVER" | grep -q '^3\.[0-5]\.'
          then
              cabal v1-update
          else
              cabal v2-update
          fi
          cabal v1-install --only-dependencies
          cabal v1-configure
          cabal v1-build
          cabal v2-sdist --builddir=dist
          SRC_TGZ=$(cabal info . | awk '{print $2; exit}').tar.gz &&
              (cd dist/sdist && cabal v1-install --force-reinstalls "$SRC_TGZ")
          echo 'module Main where main = putStrLn "Ok"' |
              ghc --frontend GhcStdin -ffrontend-opt="-o simple_ok"
          test $(./simple_ok) = Ok
          set +e

